#!/usr/bin/python

'''
Simple json-rpc daemon, compatible with SPDK rpc

Copyright (c) 2021 by Hannes Reinecke, SUSE Linux LLC

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
'''

from __future__ import print_function

import os
import sys
import json
import socket
import kmod
import argparse
import base64
import uuid as UUID
import nvmet as nvme
try:
    from BaseHTTPServer import HTTPServer, BaseHTTPRequestHandler
except ImportError:
    from http.server import HTTPServer
    from http.server import BaseHTTPRequestHandler

nvmet_sock = '/var/tmp/nvmet.sock'
nvmet_url = '/nvmet'

class BlockDevice:
    _path_prefix = dict( malloc='/dev/shm/', lvol='/srv/longhorn/')

    def __init__(self, name, uuid = None, type = 'any', mode = 'lookup'):
        self.name = name
        if type == 'any':
            if mode == 'create':
                raise NameError("Need to specify a mode for 'lookup'")
        elif type not in BlockDevice._path_prefix:
            raise NameError("Invalid bdev type %s" % type)

        if mode == 'lookup':
            if type == 'any':
                for p in BlockDevice._path_prefix:
                    self.prefix = BlockDevice._path_prefix[p]
                    if os.path.exists(self.prefix + name):
                        self.link_path = self.prefix + name
                        break
                if not self.link_path:
                    raise NameError("bdev %s not found" % name)
            else:
                self.prefix = BlockDevice._path_prefix[type]
                self.link_path = self.prefix + name
                if not os.path.exists(self.link_path):
                    raise NameError("%s bdev %s not found" % (type, name))
            try:
                self.uuid_path = os.readlink(self.link_path)
            except FileNotFoundError:
                raise RuntimeError("UUID symlink for bdev %s not found" % name)
            self.uuid = self.uuid_path[len(self.prefix):]
        else:
            self.prefix = BlockDevice._path_prefix[type]
            self.link_path = self.prefix + name
            if os.path.exists(self.prefix + name):
                raise NameError("%s bdev %s already exists" % (type, name))
            if uuid is None:
                self.uuid = str(UUID.uuid4())
            else:
                self.uuid = uuid
            self.uuid_path = self.prefix + self.uuid
            if os.path.exists(self.uuid_path):
                raise NameError("bdev %s already exists" % self.uuid_path)
            try:
                fd = open(self.uuid_path, 'x')
            except:
                raise NameError("Cannot create %s" % self.uuid_path)
            fd.close()
            try:
                os.symlink(self.uuid_path, self.link_path)
            except:
                raise RuntimeError("Failed to link %s to %s" % (self.link_path, self.uuid_path))

    def delete(self):
        try:
            os.remove(self.link_path)
        except FileNotFoundError:
            raise RuntimeError("link %s does not exist" % self.link_path)
        try:
            os.remove(self.uuid_path)
        except FileNotFoundError:
            raise RuntimeError("bdev %s does not exist" % self.uuid_path)

    def snapshot(self, clone, uuid=None):
        if not uuid:
            uuid = str(UUID.uuid4())
        clone_uuid_path = self.prefix + uuid
        if os.path.exists(clone_uuid_path):
            raise NameError("snapshot uuid %s already exists" % uuid)
        clone_link_path = self.prefix + clone
        if os.path.exists(clone_link_path):
            raise NameError("snapshot %s already exists" % clone)
        try:
            os.system("cp --reflink %s %s" % (self.uuid_path, clone_uuid_path) )
        except:
            raise RuntimeError("failed to clone bdev %s to %s" % (self.uuid_path, clone_uuid_path))
        try:
            os.symlink(clone_uuid_path, clone_link_path)
        except:
            raise RuntimeError("failed to link %s to %s" % (clone_link_path, clone_uuid_path))
        return clone

    def set_size(self, bdev_size):
        self.bdev_size = bdev_size
        try:
            os.truncate(self.uuid_path, self.bdev_size)
        except:
            raise RuntimeError("Failed to truncate %s" % self.uuid_path)

class NvmetJsonRPC:
    def _get_subsystems(self, params = None):
        return [s.dump() for s in self.cfg.subsystems]

    def _get_transports(self, params = None):
        km = kmod.Kmod()
        ml = []
        for m in km.loaded():
            if m.name.startswith("nvmet_"):
                ml.append(m.name[len("nvmet_"):])
            elif m.name == "nvme_loop":
                ml.append(m.name[len("nvme_"):])
        return ml

    def _create_transport(self, params):
        km = kmod.Kmod()
        trtype = params['trtype']
        if trtype.lower() == 'loop':
            prefix = "nvme_"
        else:
            prefix = "nvmet_"
        try:
            km.modprobe(prefix + trtype.lower())
        except:
            raise NameError("Module %s%s not found" % (prefix, trtype.lower()))

    def _create_subsystem(self, params):
        nqn = params['nqn']
        try:
            subsys = nvme.Subsystem(nqn, mode='create')
        except:
            raise RuntimeError("Failed to create subsystem %s" % nqn)
        if 'model_number' in params:
            model = params['model_number']
            if (len(model) > 40):
                subsys.delete()
                raise NameError("Model number longer than 40 characters")
            try:
                subsys.set_attr("attr", "model", model)
            except:
                subsys.delete()
                raise RuntimeError("Failed to set model %s" % model)
        if 'serial_number' in params:
            serial = params['serial_number']
            if len(serial) > 20:
                subsys.delete()
                raise NameError("Serial number longer than 20 characters")
            try:
                subsys.set_attr("attr", "serial", serial)
            except:
                subsys.delete()
                raise RuntimeError("Failed to set serial %s" % serial)
        if 'allow_any_host' in params:
            subsys.set_attr("attr", "allow_any_host", "1")

    def _delete_subsystem(self, params):
        nqn = params['nqn']
        try:
            subsys = nvme.Subsystem(nqn, mode='lookup');
        except CFSError:
            raise NameError("Subsystem %s not found" % nqn)
        try:
            subsys.delete()
        except:
            raise RuntimeError("Failed to delete subsystem %s" % nqn)

    def _add_ns(self, params):
        nqn = params['nqn']
        ns_params = params['namespace']
        bdev_name = ns_params['bdev_name']
        try:
            bdev = BlockDevice(bdev_name)
        except:
            raise NameError("bdev %s not found" % bdev_name)
        try:
            subsys = nvme.Subsystem(nqn, mode='lookup')
        except CFSError:
            raise NameError("Subsystem %s not found" % nqn)

        if 'nsid' in ns_params:
            nsid = ns_params['nsid']

        try:
            ns = nvme.Namespace(subsys, nsid, mode='create')
        except:
            raise NameError("Namespace %s already exists" % nsid)
        try:
            ns.set_attr("device", "uuid", bdev.uuid)
        except:
            ns.delete()
            raise RuntimeError("Failed to set uuid %s on ns %s" % (bdev.uuid, nsid))
        try:
            ns.set_attr("device", "path", bdev.uuid_path)
        except:
            ns.delete()
            raise RuntimeError("Failed to set path on ns %s" % nsid)
        try:
            ns.set_enable(1)
        except:
            raise RuntimeError("Failed to enable ns %s" % nsid)

    def _remove_ns(self, params):
        nqn = params['nqn']
        nsid = params['nsid']
        try:
            subsys = nvme.Subsystem(nqn, mode='lookup')
        except CFSError:
            raise NameError("Subsystem %s not found" % nqn)
        try:
            ns = nvme.Namespace(subsys, nsid, mode='lookup')
        except CFSError:
            raise NameError("Namespace %d not found" % nsid)
        ns.delete()

    def _add_port(self, params):
        try:
            port = nvme.Port(mode='create')
        except:
            raise RuntimeError("Cannot create port")
        port_params = params['listen_address']
        for p in ('trtype', 'adrfam', 'traddr', 'trsvcid'):
            if p not in port_params:
                port.delete()
                raise NameError("Invalid listen_address parameter %s" % p)
            v = port_params[p]
            if p == 'adrfam':
                v = port_params[p].lower()
            try:
                port.set_attr("addr", p, v)
            except:
                port.delete()
                raise RuntimeError("Failed to set %s to %s" % (p, v))
        nqn = params['nqn']
        try:
            port.add_subsystem(nqn)
        except:
            port.delete()
            raise NameError("subsystem %s not found" % nqn)

    def _remove_port(self, params):
        nqn = params['nqn']
        port_params = params['listen_address']
        for port in self.cfg.ports:
            for p in ('trtype', 'adrfam', 'traddr', 'trsvcid'):
                if p not in port_params:
                    continue
                if port.get_attr("addr", p) != port_params[p]:
                    continue
            for s in port.subsystems:
                if s != nqn:
                    continue
                port.remove_subsystem(nqn)
                if not len(port.subsystems):
                    port.delete()

    def _add_host(self, params):
        nqn = params['nqn']
        try:
            subsys = nvme.Subsystem(nqn, mode='lookup')
        except CFSError:
            raise NameError("Subsystem %s not found" % nqn)
        host = params['host']
        try:
            subsys.add_allowed_host(host)
        except CFSError:
            return False
        return True

    def _remove_host(self, params):
        nqn = params['nqn']
        try:
            subsys = nvme.Subsystem(nqn, mode='lookup')
        except CFSError:
            raise NameError("Subsystem %s not found" % nqn)
        host = params['host']
        try:
            subsys.remove_allowed_host(host)
        except CFSError:
            return False
        return True

    def _create_malloc(self, params):
        bdev_name = params['name']
        bdev_blocksize = params['block_size']
        bdev_blocks = params['num_blocks']
        if 'uuid' in params:
            bdev_uuid = params['uuid']
        else:
            bdev_uuid = None

        bdev = BlockDevice(bdev_name, bdev_uuid, type='malloc', mode='create')
        bdev.set_size(int(bdev_blocks) * int(bdev_blocksize))
        return bdev.name

    def _delete_malloc(self, params):
        bdev_name = params['name']
        bdev = BlockDevice(bdev_name, type='malloc')
        bdev.delete()

    def _create_lvol(self, params):
        bdev_name = params['lvol_name']
        bdev_size = params['size']
        if 'uuid' in params:
            bdev_uuid = params['uuid']
        else:
            bdev_uuid = None

        bdev = BlockDevice(bdev_name, bdev_uuid, type='lvol', mode='create')
        bdev.set_size(int(bdev_size))
        return bdev.name

    def _delete_lvol(self, params):
        bdev_name = params['name']
        bdev = BlockDevice(bdev_name, type='lvol')
        bdev.delete()

    def _snapshot_lvol(self, params):
        lvol = params['lvol_name']
        snap = params['snapshot_name']
        bdev = BlockDevice(lvol, type='lvol')
        return bdev.snapshot(snap)

    def _clone_lvol(self, params):
        snap = params['snapshot_name']
        clone = params['clone_name']
        bdev = BlockDevice(snap, type='lvol')
        return bdev.snapshot(clone)

    def _get_lvolstores(self, params):
        if params:
            if 'uuid' in params:
                lvs_uuid = params['uuid']
            if 'lvs_name' in params:
                lvs_name = params['lvs_name']
        st = os.statvfs(BlockDevice._path_prefix['lvol'])
        return dict(name='longhorn',
                    cluster_size=st.f_frsize,
                    free_clusters=st.f_bavail,
                    total_data_clusters=st.f_blocks)

    _rpc_methods = dict(bdev_malloc_create=_create_malloc,
                        bdev_malloc_delete=_delete_malloc,
                        bdev_lvol_create=_create_lvol,
                        bdev_lvol_delete=_delete_lvol,
                        bdev_lvol_snapshot=_snapshot_lvol,
                        bdev_lvol_clone=_clone_lvol,
                        bdev_lvol_get_lvstores=_get_lvolstores,
                        nvmf_create_transport=_create_transport,
                        nvmf_get_transports=_get_transports,
                        nvmf_create_subsystem=_create_subsystem,
                        nvmf_delete_subsystem=_delete_subsystem,
                        nvmf_subsystem_add_ns=_add_ns,
                        nvmf_subsystem_remove_ns=_remove_ns,
                        nvmf_subsystem_add_listener=_add_port,
                        nvmf_subsystem_remove_listener=_remove_port,
                        nvmf_subsystem_add_host=_add_host,
                        nvmf_subsystem_remove_host=_remove_host,
                        nvmf_get_subsystems=_get_subsystems)

    def __init__(self):
        self.cfg = nvme.Root()

    def rpc_call(self, req):
        print ("%s" % req)
        method = req['method']
        if 'params' in req:
            params = req['params']
        else:
            params = None
        id = req['id']
        if method not in self._rpc_methods:
            error = dict(code=-32601,message='Method not found')
            resp = json.dumps(dict(error=error, id=id, jsonrpc="2.0"))
        else:
            try:
                result = self._rpc_methods[method](self, params)
                resp = json.dumps(dict(result=result, id=id, jsonrpc="2.0"))
            except NameError as n:
                error = dict(code=-32602, message='Invalid params', data=n.args)
                resp = json.dumps(dict(error=error, id=id, jsonrpc="2.0"))
            except RuntimeError as err:
                error = dict(code=-32000, message=err.args)
                resp = json.dumps(dict(error=error, id=id, jsonrpc="2.0"))
            print ("%s" % resp)
        return resp

class JSONRPC:
    def __init__(self, sockname):
        self.sockname = sockname
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            self.sock.bind(self.sockname)
        except OSError:
            print("cannot bind to %s" % self.sockname)
            return None
        self.sock.listen(10)

    def __enter__(self):
        return self

    def rpc_server(self):
        while True:
            buf = ''
            closed = False
            response = None
            (client, address) = self.sock.accept()
            while not closed:
                newdata = client.recv(1024)
                if (newdata == b''):
                    closed = True
                buf += newdata.decode('ascii')
                try:
                    req = json.loads(buf)
                except ValueError:
                    continue
                rpc = NvmetJsonRPC()
                response = rpc.rpc_call(req)
                client.sendall(response.encode('ascii'))
                client.close()
                closed = True

    def rpc_shutdown(self):
        self.sock.close()

    def __exit__(self, exc_type, exc_value, traceback):
        os.remove(self.sockname)

class ServerHandler(BaseHTTPRequestHandler):
    key = ""

    def do_HEAD(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()

    def do_AUTHHEAD(self):
        self.send_response(401)
        self.send_header('WWW-Authenticate', 'text/html')
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_INTERNALERROR(self):
        self.send_response(500)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_NOTFOUND(self):
        self.send_response(404)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_POST(self):
        if self.path != self.directory:
            self.do_NOTFOUND()
            return
        if self.key and self.headers['Authorization'] != 'Basic ' + self.key:
            self.do_AUTHHEAD()
        else:
            data_string = self.rfile.read(int(self.headers['Content-Length']))

            try:
                req = json.loads(data_string)
            except ValueError:
                self.do_INTERNALERROR()
                return
            rpc = NvmetJsonRPC()
            response = rpc.rpc_call(req)
            self.do_HEAD()
            self.wfile.write(bytes(response.encode(encoding='ascii')))

def main():
    parser = argparse.ArgumentParser(description='JSON RPC proxy for nvmet')
    parser.add_argument('-s', '--socket', dest='sock', default=nvmet_sock,
                        help="Socket to listen on, default is " + nvmet_sock)
    parser.add_argument('-H', '--host', dest='host', help='Host address')
    parser.add_argument('-p', '--port', dest='port', type=int, default=4260,
                        help='Port number')
    parser.add_argument('-U', '--user', dest='user',
                        help='user name for authentication')
    parser.add_argument('-P', '--password', dest='password',
                        help='password for authentication')
    parser.add_argument('-c', '--cert', dest='cert',
                        help='SSL certificate')
    parser.add_argument('-u', '--url', dest='url', default=nvmet_url,
                        help="URL path to serve, default is " + nvmet_url)

    args = parser.parse_args()
    if args.user and not args.password:
        sys.exit("No password specified for username %s" % args.user)
    if args.password and not args.user:
        sys.exit("No username specified")
    if args.user:
        if not args.host:
            sys.exit("Username and password are only valid for HTTP server")
        key = base64.b64encode(bytes('%s:%s' % (args.user, args.password), 'utf-8')).decode('ascii')
        ServerHandler.key = key

    if args.url:
        ServerHandler.directory = args.url

    if os.geteuid() != 0:
       print("%s: must run as root." % sys.argv[0], file=sys.stderr)
       sys.exit(-1)


    if args.host:
        with HTTPServer((args.host, args.port), ServerHandler) as httpd:
            try:
                if args.cert is not None:
                    http.socket = ssl.wrap_socket(httpd.socket,
                                                  certfile=args.cert,
                                                  server_side=True)
                print("Started JSON RPC http proxy server on %s:%d key %s" % (args.host, args.port, key))
                httpd.serve_forever()
            except KeyboardInterrupt:
                print("Shutting down server")
                httpd.socket.close()
    else:
        with JSONRPC(args.sock) as s:
            try:
                print("Started JSON RPC proxy server on %s" % args.sock)
                s.rpc_server()
            except KeyboardInterrupt:
                print('Shutting down server')
                s.rpc_shutdown()

if __name__ == '__main__':
    main()
